name: userapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.3
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_image_compress: ^2.4.0
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  fpdart: ^1.1.1
  google_fonts: ^6.2.1
  image: ^4.5.2
  image_picker: ^1.1.2
  mockito: ^5.4.5
  path_provider: ^2.1.5
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.4.0
  test: ^1.25.8

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/button/
    - assets/logo/

flutter_native_splash:
  color: "#CC8FED"
  image: assets/logo/app_logo.png

  android_12:
    color: "#CC8FED"
    branding: assets/logo/app_logo.png

  android: true
  ios: true
